// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYhDzvCI06d0aM4cUKSVgwE5a5KBlawA0',
    appId: '1:1086586579041:web:433aefc3eec0ed1b7aa220',
    messagingSenderId: '1086586579041',
    projectId: 'pikawatt-af722',
    authDomain: 'pikawatt-af722.firebaseapp.com',
    storageBucket: 'pikawatt-af722.firebasestorage.app',
    measurementId: 'G-TDMT4QLE4C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsboVrGeL1MQD2-o9IEoKWRxiRfhpOz_0',
    appId: '1:1086586579041:android:a87f1b1354b6d9837aa220',
    messagingSenderId: '1086586579041',
    projectId: 'pikawatt-af722',
    storageBucket: 'pikawatt-af722.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-BPj6Tg2uYeViRlN8cvXjfk7Q2dBk3ns',
    appId: '1:1086586579041:ios:4bd455a05ce967c27aa220',
    messagingSenderId: '1086586579041',
    projectId: 'pikawatt-af722',
    storageBucket: 'pikawatt-af722.firebasestorage.app',
    iosBundleId: 'com.example.projectPhase2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-BPj6Tg2uYeViRlN8cvXjfk7Q2dBk3ns',
    appId: '1:1086586579041:ios:4bd455a05ce967c27aa220',
    messagingSenderId: '1086586579041',
    projectId: 'pikawatt-af722',
    storageBucket: 'pikawatt-af722.firebasestorage.app',
    iosBundleId: 'com.example.projectPhase2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYhDzvCI06d0aM4cUKSVgwE5a5KBlawA0',
    appId: '1:1086586579041:web:2fc803c39f7e6fe57aa220',
    messagingSenderId: '1086586579041',
    projectId: 'pikawatt-af722',
    authDomain: 'pikawatt-af722.firebaseapp.com',
    storageBucket: 'pikawatt-af722.firebasestorage.app',
    measurementId: 'G-SFKVLS2LLX',
  );
}
