name: pikawatt
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.0

dependencies:
  cloud_firestore: ^6.2.0
  firebase_auth: ^6.3.0
  firebase_core: ^4.6.0
  fl_chart: ^1.2.0
  flutter:
    sdk: flutter
  geolocator: ^14.0.2
  http: ^1.6.0
  provider: ^6.1.5+1
  shared_preferences: ^2.5.5
  sqflite: ^2.4.2
  sqflite_common_ffi_web: ^1.1.1
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
  - pictures/PikaWatt_Logo.png
